### ISSUE TITLE
Eliminar variables de DR

### ISSUE THREAD

**Issue by rortega-sps** [spsmexico/aws_sam_github_quickstart_template#13]
> Trabajar en la rama **demo**

Objetivo: Eliminar las variables para las llaves de la región dr en la plantilla de cookiecutter.

Las llaves multi región son iguales. Lo único que cambia es la región:

```
Primary key: arn:aws:kms:us-east-1:111122223333:key/mrk-1234abcd12ab34cd56ef12345678990ab
Replica key: arn:aws:kms:eu-west-1:111122223333:key/mrk-1234abcd12ab34cd56ef12345678990ab
```
https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html#mrk-how-it-works

Se podría ingresar solo una vez el ARN para la llave de la región primaria: 
https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/b31614ecd591ab729f90fe3d06c6f94c966f2be0/cookiecutter.json#L8

Eliminando la variable de DR:
https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/b31614ecd591ab729f90fe3d06c6f94c966f2be0/cookiecutter.json#L11

Cookiecutter utiliza Jinja2 como motor de plantillas y soporta una función para replazar valores en una cadena:

Plantilla:
`{{ 'aaabbbccc'|replace('b', '.') }}`

Salida:
`aaa...ccc`

Validar si es posible aplicarlo a los archivos [parameters-dev-dr.json](https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/demo/%7B%7Bcookiecutter.nombre_repo%7D%7D/parameters-dev-dr.json), [parameters-pre-dr.json](https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/demo/%7B%7Bcookiecutter.nombre_repo%7D%7D/parameters-pre-dr.json) y [parameters-prod-dr.json](https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/demo/%7B%7Bcookiecutter.nombre_repo%7D%7D/parameters-prod-dr.json)
https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/b31614ecd591ab729f90fe3d06c6f94c966f2be0/%7B%7Bcookiecutter.nombre_repo%7D%7D/parameters-dev-dr.json#L4

Puedes apoyarte de:
- http://jinja.quantprogramming.com/
- https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.replace

**Comment by RicardoAOrtegaGarcia** [comment]
Usar las variables que ya tiene la plantilla, buscar_
https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/b1abf553ba98891ad1a1a75c9b8efe92eb8c3053/cookiecutter.json#L6

Remplazar su valor por:
https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/b1abf553ba98891ad1a1a75c9b8efe92eb8c3053/cookiecutter.json#L7

**Comment by RicardoAOrtegaGarcia** [comment]
Usar las variables que ya tiene la plantilla, buscar:
https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/b1abf553ba98891ad1a1a75c9b8efe92eb8c3053/cookiecutter.json#L6

Remplazar su valor por:
https://github.com/spsmexico/aws_sam_github_quickstart_template/blob/b1abf553ba98891ad1a1a75c9b8efe92eb8c3053/cookiecutter.json#L7
